Repository Katchup-dev/Katchup-client, pull requests merged in 2023-10, with the labels that each got.

#73 [🧑🏻‍💻 GA-Setting] GA 추적 코드 심기
  pages/_app.tsx
Labels: 🧑🏻‍💻GA-Setting

#76 [ 👋🏻 SignUp ] 토큰 에러 분기처리
  constants/error.ts
  core/apis/token.ts
  lib/axios.ts
  pages/_app.tsx
Labels: 🔓Signup, 코드리뷰

#78 [ 👨🏻‍💻 Setting ] 설정 뷰, 도움 뷰 구현
  components/Landing/LandingKatchupStart.tsx
  components/common/Header.tsx
  components/common/Header/Header.tsx
  components/common/Header/Help/Help.tsx
  components/common/Header/Help/index.ts
  components/common/Header/LogoHeader/LogoHeader.tsx
  components/common/Header/LogoHeader/index.tsx
  components/common/Header/Nav/Nav.tsx
  components/common/Header/Nav/index.tsx
  components/common/Header/Profile/InputImage.tsx
  components/common/Header/Profile/InputMemo.tsx
  components/common/Header/Profile/InputNickname.tsx
  components/common/Header/Profile/ProfileSettingModal.tsx
  components/common/Header/Profile/index.ts
  components/common/Header/Setting/Setting.tsx
  components/common/Header/Setting/index.ts
  components/common/Header/Utility/SearchBox.tsx
  components/common/Header/Utility/Utility.tsx
  components/common/Header/Utility/index.ts
  components/common/Header/index.ts
  components/input/InputBasic/FileInput.tsx
  components/input/InputBasic/MainInput.tsx
  components/input/InputBasic/WorkInput.tsx
  components/input/InputCard/ModalCard.tsx
  components/input/InputCard/ModalInput.tsx/InputCategory.tsx
  components/input/InputCard/ModalInput.tsx/InputEtc.tsx
  components/withdraw/CheckBox.tsx
  components/withdraw/Withdraw.tsx
  components/withdraw/WithdrawComplete.tsx
  components/withdraw/WithdrawReason.tsx
  components/withdraw/index.ts
  constants/footer.ts
  constants/katchupDefault.ts
  constants/withdraw.ts
  core/apis/auth.ts
  core/atom.ts
  lib/hooks/common/useClickOutside.ts
  lib/hooks/common/useModal.ts
  lib/hooks/user/useGetProfile.ts
  package.json
  pages/_app.tsx
  pages/output/[mainId]/index.tsx
  pages/share/[mainId]/index.tsx
  pages/withdraw/complete/index.tsx
  pages/withdraw/index.tsx
  public/assets/icons/ic_btn_logout.svg
  public/assets/icons/ic_btn_profile.svg
  public/assets/icons/ic_check_after.svg
  public/assets/icons/ic_check_before.svg
  public/assets/icons/index.ts
  types/auth.ts
Labels: 👨🏻‍💻 Setting
